include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_print: true
    avoid_unnecessary_containers: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    sized_box_for_whitespace: true
    use_super_parameters: true
    unnecessary_this: true
    unnecessary_new: true
    sort_child_properties_last: true

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
